In [1]:
import PIL
from PIL import Image
import numpy as np
import cv2 as cv

In [2]:
sem_file = 'SEM_06_06.png'
num_classes = 13

palette = {
    0: [0, 0, 0],  # None
    1: [70, 70, 70],  # Buildings
    2: [190, 153, 153],  # Fences
    3: [72, 0, 90],  # Other
    4: [220, 20, 60],  # Pedestrians
    5: [153, 153, 153],  # Poles
    6: [157, 234, 50],  # RoadLines
    7: [128, 64, 128],  # Roads
    8: [244, 35, 232],  # Sidewalks
    9: [107, 142, 35],  # Vegetation
    10: [0, 0, 255],  # Vehicles
    11: [102, 102, 156],  # Walls
    12: [220, 220, 0],  # TrafficSigns
    13: [150, 33, 88],  # TrafficSigns
    }
for i in range(len(palette), 256):
    palette[i] = [0, 0, 0]

palette_list = [] 
for v in palette.values():
    for i in range(3):
        palette_list.append(v[i])
# palette_list

In [3]:
# Lets load a carla semantic map
seg = cv.imread(sem_file, cv.IMREAD_ANYCOLOR |
                cv.IMREAD_ANYDEPTH)
seg = np.asarray(seg, dtype=np.uint8)[:, :, 2]
print(np.unique(seg))
print(seg.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12]
(600, 800)


In [4]:
# now we will save this semantic map with a pallete
im_pil = Image.fromarray(seg, mode="P")
# if we save it now it will not be displayed correctly
im_pil.putpalette(palette_list)
im_pil.save('colored_sem.png')
im_pil.close()
# Now open see this file in image viewer

In [37]:
# The image is colored, good for visualisation
# can we load it and get the coorect label ids
im_pil = Image.open('colored_sem.png')
seg = np.array(im_pil)
print(np.unique(seg))
print(seg.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12]
(600, 800)


In [6]:
# The image is colored, good for visualisation
# can we load it and get the coorect label ids
im_pil = Image.open('colored_sem_edited.png')
seg = np.array(im_pil)
print(np.unique(seg))
print(seg.shape)
im_pil.save('a.png')
im_pil.close()

[ 0  1  2  3  4  5  6  7  8  9 10 11 12]
(600, 800)
